package astronomy

import astronomy.PlanetKind.GasGiant
import astronomy.PlanetKind.IceGiant
import astronomy.PlanetKind.Terrestrial


interface AstronomicalBody {
    val name: String
}

data class DwarfPlanet(override val name: String) : AstronomicalBody
data class Moon(override val name: String) : AstronomicalBody
enum class PlanetKind { Terrestrial, GasGiant, IceGiant }
data class Planet(override val name: String,
                  val kind: PlanetKind,
                  val moons: Collection<Moon>,
                  val ring: Boolean) : AstronomicalBody

data class Star(override val name: String) : AstronomicalBody


object SolarSystem {
    val bodies: Collection<AstronomicalBody> =
        listOf(
            DwarfPlanet(name = "Ceres"),
            DwarfPlanet(name = "Pluto"),
            Planet(name = "Mercury", kind = Terrestrial, moons = emptyList(), ring = false),
            Planet(name = "Venus", kind = Terrestrial, moons = emptyList(), ring = false),
            Planet(name = "Earth", kind = Terrestrial, moons = listOf(Moon("Moon")), ring = false),
            Planet(name = "Mars",
                   kind = Terrestrial,
                   moons = listOf(Moon("Phobos"), Moon("Deimos")),
                   ring = false),
            Planet(name = "Jupiter", kind = GasGiant, moons = listOf(
                Moon("Metis"),
                Moon("Adrastea"),
                Moon("Amalthea"),
                Moon("Thebe"),
                Moon("Io"),
                Moon("Europa"),
                Moon("Ganymede"),
                Moon("Callisto"),
                Moon("Themisto"),
                Moon("Leda"),
                Moon("Himalia"),
                Moon("Lysithea"),
                Moon("Elara"),
                Moon("Dia"),
                Moon("Carpo"),
                Moon("S/2003"),
                Moon("Euporie"),
                Moon("S/2003"),
                Moon("S/2011"),
                Moon("S/2003"),
                Moon("S/2010"),
                Moon("Thelxinoe"),
                Moon("Euanthe"),
                Moon("Helike"),
                Moon("Orthosie"),
                Moon("S/2016"),
                Moon("Iocaste"),
                Moon("S/2003"),
                Moon("Praxidike"),
                Moon("Harpalyke"),
                Moon("Mneme"),
                Moon("Hermippe"),
                Moon("Thyone"),
                Moon("Ananke"),
                Moon("Herse"),
                Moon("Aitne"),
                Moon("Kale"),
                Moon("Taygete"),
                Moon("S/2003"),
                Moon("Chaldene"),
                Moon("S/2003"),
                Moon("S/2003"),
                Moon("S/2003"),
                Moon("Erinome"),
                Moon("Aoede"),
                Moon("Kallichore"),
                Moon("Kalyke"),
                Moon("Carme"),
                Moon("Callirrhoe"),
                Moon("Eurydome"),
                Moon("Pasithee"),
                Moon("S/2010"),
                Moon("Kore"),
                Moon("Cyllene"),
                Moon("S/2011"),
                Moon("Eukelade"),
                Moon("S/2017"),
                Moon("S/2003"),
                Moon("Pasiphae"),
                Moon("Hegemone"),
                Moon("Arche"),
                Moon("Isonoe"),
                Moon("S/2003"),
                Moon("S/2003"),
                Moon("Sinope"),
                Moon("Sponde"),
                Moon("Autonoe"),
                Moon("Megaclite"),
                Moon("S/2003")
            ), ring = true),
            Planet(name = "Saturn", kind = GasGiant, moons = listOf(
                Moon("S/2009 S 1"),
                Moon("Pan"),
                Moon("Daphnis"),
                Moon("Atlas"),
                Moon("Prometheus"),
                Moon("Pandora"),
                Moon("Epimetheus"),
                Moon("Janus"),
                Moon("Aegaeon"),
                Moon("Mimas"),
                Moon("Methone"),
                Moon("Anthe"),
                Moon("Pallene"),
                Moon("Enceladus"),
                Moon("Tethys"),
                Moon("Telesto"),
                Moon("Calypso"),
                Moon("Dione"),
                Moon("Helene"),
                Moon("Polydeuces"),
                Moon("Rhea"),
                Moon("Titan"),
                Moon("Hyperion"),
                Moon("Iapetus"),
                Moon("Kiviuq"),
                Moon("Ijiraq"),
                Moon("Phoebe"),
                Moon("Paaliaq"),
                Moon("Skathi"),
                Moon("Albiorix"),
                Moon("S/2007 S 2"),
                Moon("Bebhionn"),
                Moon("Erriapus"),
                Moon("Skoll"),
                Moon("Siarnaq"),
                Moon("Tarqeq"),
                Moon("S/2004 S 13"),
                Moon("Greip"),
                Moon("Hyrrokkin"),
                Moon("Jarnsaxa"),
                Moon("Tarvos"),
                Moon("Mundilfari"),
                Moon("S/2006 S 1"),
                Moon("S/2004 S 17"),
                Moon("Bergelmir"),
                Moon("Narvi"),
                Moon("Suttungr"),
                Moon("Hati"),
                Moon("S/2004 S 12"),
                Moon("Farbauti"),
                Moon("Thrymr"),
                Moon("Aegir"),
                Moon("S/2007 S 3"),
                Moon("Bestla"),
                Moon("S/2004 S 7"),
                Moon("S/2006 S 3"),
                Moon("Fenrir"),
                Moon("Surtur"),
                Moon("Kari"),
                Moon("Ymir"),
                Moon("Loge"),
                Moon("Fornjot")
            ), ring = true),
            Planet(name = "Uranus", kind = IceGiant, moons = listOf(
                Moon("Cordelia"),
                Moon("Ophelia"),
                Moon("Bianca"),
                Moon("Cressida"),
                Moon("Desdemona"),
                Moon("Juliet"),
                Moon("Portia"),
                Moon("Rosalind"),
                Moon("Cupid"),
                Moon("Belinda"),
                Moon("Perdita"),
                Moon("Puck"),
                Moon("Mab"),
                Moon("Miranda"),
                Moon("Ariel"),
                Moon("Umbriel"),
                Moon("Titania"),
                Moon("Oberon"),
                Moon("Francisco"),
                Moon("Caliban"),
                Moon("Stephano"),
                Moon("Trinculo"),
                Moon("Sycorax"),
                Moon("Margaret"),
                Moon("Prospero"),
                Moon("Setebos"),
                Moon("Ferdinand")
            ), ring = true),
            Planet(name = "Neptune", kind = IceGiant, moons = listOf(
                Moon("Naiad"),
                Moon("Thalassa"),
                Moon("Despina"),
                Moon("Galatea"),
                Moon("Larissa"),
                Moon("S/2004 N 1"),
                Moon("Proteus"),
                Moon("Triton"),
                Moon("Nereid"),
                Moon("Halimede"),
                Moon("Sao"),
                Moon("Laomedeia"),
                Moon("Psamathe"),
                Moon("Neso")
            ), ring = true),
            Star(name = "Sun")
        )
}

